fn main() {
    let target = std::env::var("TARGET").expect("Cargo did not provide TARGET");
    if target == "x86_64-apple-darwin" {
        panic!("Intel macOS builds are unsupported; build aarch64-apple-darwin instead");
    }
    println!("cargo:rustc-env=DUSORI_TARGET_TRIPLE={target}");
    println!("cargo:rerun-if-env-changed=DUSORI_UPDATER_PUBLIC_KEY");
    println!("cargo:rerun-if-changed=updater.release.json");

    let key = std::env::var("DUSORI_UPDATER_PUBLIC_KEY")
        .unwrap_or_else(|_| "DUSORI_UPDATER_PUBLIC_KEY_NOT_PROVISIONED".into());
    println!("cargo:rustc-env=DUSORI_UPDATER_PUBLIC_KEY={}", key.trim());

    if std::env::var("PROFILE").as_deref() == Ok("release") {
        if key.trim().is_empty() || key.contains("NOT_PROVISIONED") {
            panic!(
                "release builds require DUSORI_UPDATER_PUBLIC_KEY; generate the updater key offline and commit only its public key"
            );
        }
        let release_config = std::path::Path::new(&std::env::var("CARGO_MANIFEST_DIR").unwrap())
            .join("updater.release.json");
        let release_config: serde_json::Value = serde_json::from_slice(
            &std::fs::read(&release_config).expect(
                "release builds require the ignored updater.release.json overlay generated by verify-desktop-release.mjs",
            ),
        )
        .expect("the updater release overlay must be valid JSON");
        let configured_key = release_config
            .pointer("/plugins/updater/pubkey")
            .and_then(serde_json::Value::as_str)
            .unwrap_or_default();
        if configured_key != key.trim() {
            panic!(
                "the updater release overlay public key must exactly match DUSORI_UPDATER_PUBLIC_KEY"
            );
        }
        let endpoint = release_config
            .pointer("/plugins/updater/endpoints/0")
            .and_then(serde_json::Value::as_str)
            .unwrap_or_default();
        if endpoint != "https://github.com/udhawan97/Dusori/releases/latest/download/latest.json" {
            panic!("the updater release overlay must retain Dusori's fixed GitHub endpoint");
        }
    }

    tauri_build::build()
}
