import type { ResearchCandidateKind, ResearchQuery } from './types.js';

export interface BriefSource {
  title: string;
  url: string;
  providerLabel: string;
  /** Why the ranker put this source in front of the user, in its own words. */
  reasons: string[];
  kind?: ResearchCandidateKind;
}

export interface BriefOptions {
  /** True when an AI provider was configured but could not be reached for this brief. */
  aiUnavailable?: boolean;
}

const kindHeadings: Record<ResearchCandidateKind, string> = {
  article: 'Articles',
  course: 'Courses',
  docs: 'Documentation',
  paper: 'Papers',
  qa: 'Questions and answers',
  repo: 'Repositories',
};

const kindOrder: ResearchCandidateKind[] = ['docs', 'course', 'paper', 'article', 'repo', 'qa'];

export function briefNoteTitle(query: ResearchQuery, now: Date): string {
  const objective = query.objectiveTitle || query.topicTitle;
  return `Research brief — ${objective} — ${now.toISOString().slice(0, 10)}`;
}

function groupByKind(sources: BriefSource[]): [string, BriefSource[]][] {
  const groups = new Map<string, BriefSource[]>();
  for (const source of sources) {
    const heading = source.kind ? kindHeadings[source.kind] : 'Other';
    groups.set(heading, [...(groups.get(heading) ?? []), source]);
  }
  const ordered = [...kindOrder.map((kind) => kindHeadings[kind]), 'Other'];
  return ordered.flatMap((heading) => {
    const group = groups.get(heading);
    return group ? [[heading, group] as [string, BriefSource[]]] : [];
  });
}

function sourceLines(source: BriefSource): string[] {
  const reasons = source.reasons.length > 0 ? ` — ${source.reasons.join(' · ')}` : '';
  return [`- [${source.title}](${source.url})`, `  ${source.providerLabel}${reasons}`];
}

/**
 * The honest brief: it orders and explains what the user approved, and says outright that it
 * never read the pages. Anything more would be prose the workspace cannot back up.
 */
export function buildDeterministicBrief(
  query: ResearchQuery,
  sources: BriefSource[],
  now: Date,
  options: BriefOptions = {},
): string {
  if (sources.length === 0) {
    throw new Error('Approve at least one source before writing a research brief.');
  }
  const title = briefNoteTitle(query, now);
  const groups = groupByKind(sources);
  const count = sources.length;
  const plural = count === 1 ? 'source' : 'sources';

  return [
    '---',
    `title: ${JSON.stringify(title)}`,
    `topic: ${query.topicTitle}`,
    `created: ${now.toISOString().slice(0, 10)}`,
    'generated: research-brief',
    '---',
    '',
    `# ${title}`,
    '',
    `Generated by the research agent on ${now.toISOString().slice(0, 10)} from the ${count} ${plural} you approved for **${query.objectiveTitle}**.`,
    '',
    ...(options.aiUnavailable
      ? ['AI was unavailable for this brief, so it lists what was found without commentary.', '']
      : []),
    '## Reading order',
    '',
    ...groups.flatMap(([heading, group]) => [
      `### ${heading}`,
      '',
      ...group.flatMap(sourceLines),
      '',
    ]),
    '## What this brief is',
    '',
    'The agent ranked these on public signals — search relevance, community score, publication date, and the source host — and has not read the pages themselves. Read them and replace this list with your own notes.',
    '',
  ].join('\n');
}
