import { describe, expect, it } from 'vitest';

import {
  briefNoteTitle,
  buildAiBrief,
  buildDeterministicBrief,
  type BriefSource,
} from './brief.js';
import { buildResearchQuery } from './plan.js';

const query = buildResearchQuery('TypeScript', { title: 'Understand generics' });
const now = new Date('2026-07-21T10:00:00.000Z');

const sources: BriefSource[] = [
  {
    kind: 'docs',
    providerLabel: 'Wikipedia',
    reasons: ['matches 2 objective terms', 'official documentation'],
    title: 'Generic programming',
    url: 'https://en.wikipedia.org/?curid=12345',
  },
  {
    kind: 'repo',
    providerLabel: 'GitHub',
    reasons: ['4.2k stars'],
    title: 'type-challenges/type-challenges',
    url: 'https://github.com/type-challenges/type-challenges',
  },
];

describe('briefNoteTitle', () => {
  it('names the note after the objective and the run date', () => {
    expect(briefNoteTitle(query, now)).toBe('Research brief — Understand generics — 2026-07-21');
  });
});

describe('buildDeterministicBrief', () => {
  it('marks the note as generated in its frontmatter', () => {
    const brief = buildDeterministicBrief(query, sources, now);
    expect(brief).toMatch(/^---\n/u);
    expect(brief).toContain('generated: research-brief');
    expect(brief).toContain('created: 2026-07-21');
  });

  it('says who generated it before any content', () => {
    const brief = buildDeterministicBrief(query, sources, now);
    const body = brief.split('---\n')[2] ?? '';
    expect(body).toContain('Generated by the research agent');
    expect(body).toContain('you approved');
  });

  it('lists every approved source with its link and reasons', () => {
    const brief = buildDeterministicBrief(query, sources, now);
    for (const source of sources) {
      expect(brief).toContain(source.title);
      expect(brief).toContain(source.url);
      for (const reason of source.reasons) expect(brief).toContain(reason);
    }
  });

  it('groups sources under their kind', () => {
    const brief = buildDeterministicBrief(query, sources, now);
    expect(brief).toContain('### Documentation');
    expect(brief).toContain('### Repositories');
  });

  it('states plainly that it did not read the sources', () => {
    const brief = buildDeterministicBrief(query, sources, now);
    expect(brief).toContain('has not read');
  });

  it('does not claim an AI wrote it when none did', () => {
    const brief = buildDeterministicBrief(query, sources, now);
    expect(brief.toLowerCase()).not.toContain('ai model');
  });

  it('notes when AI was configured but unavailable', () => {
    const brief = buildDeterministicBrief(query, sources, now, { aiUnavailable: true });
    expect(brief).toContain('AI was unavailable');
  });

  it('handles a source with no reasons and no kind', () => {
    const brief = buildDeterministicBrief(
      query,
      [{ providerLabel: 'Hacker News', reasons: [], title: 'A story', url: 'https://example.com' }],
      now,
    );
    expect(brief).toContain('A story');
    expect(brief).toContain('### Other');
  });

  it('refuses to build a brief with no approved sources', () => {
    expect(() => buildDeterministicBrief(query, [], now)).toThrow(/approve/iu);
  });
});

describe('buildAiBrief', () => {
  it('marks the note generated and names the model that wrote it', () => {
    const brief = buildAiBrief(query, '## Reading order\n\nStart here.', 'gemma3:4b', now);
    expect(brief).toContain('generated: research-brief');
    expect(brief).toContain('using gemma3:4b');
    expect(brief).toContain('## Reading order');
    expect(brief).toContain('not a verdict');
  });
});
