import type { TopicSynthesis } from './synthesis.js';

/**
 * Escapes text for HTML body context. Source text is untrusted data, and this page is written
 * to a file the user may open outside Dusori, where no sanitizer stands between them.
 */
function escapeHtml(value: string): string {
  return value
    .replace(/&/gu, '&amp;')
    .replace(/</gu, '&lt;')
    .replace(/>/gu, '&gt;')
    .replace(/"/gu, '&quot;')
    .replace(/'/gu, '&#39;');
}

/** Only http(s) links survive; anything else (javascript:, data:) becomes plain text. */
function safeHref(url: string | undefined): string | null {
  if (!url) return null;
  try {
    const parsed = new URL(url);
    return parsed.protocol === 'http:' || parsed.protocol === 'https:' ? parsed.toString() : null;
  } catch {
    return null;
  }
}

function sourceLine(title: string, url?: string): string {
  const href = safeHref(url);
  const label = escapeHtml(title);
  return href
    ? `<a href="${escapeHtml(href)}" target="_blank" rel="noreferrer noopener">${label}</a>`
    : label;
}

const styles = `
:root{color-scheme:light dark;--ink:#191410;--paper:#fbf7f1;--muted:#6b6058;--rule:#ddd2c6;--accent:#cb4832}
@media (prefers-color-scheme:dark){:root{--ink:#f2e9df;--paper:#14100d;--muted:#a2958a;--rule:#33291f}}
*{box-sizing:border-box}
body{margin:0;padding:1.5rem;background:var(--paper);color:var(--ink);
font:16px/1.6 ui-serif,Georgia,serif;-webkit-text-size-adjust:100%}
main{max-width:44rem;margin:0 auto}
h1{font-size:clamp(1.6rem,5vw,2.4rem);line-height:1.15;margin:0 0 .25rem}
h2{font-size:1.3rem;margin:2.5rem 0 .5rem;padding-top:1rem;border-top:1px solid var(--rule)}
h3{font-size:1.05rem;margin:1.5rem 0 .5rem}
p,li{max-width:38rem}
.lede{color:var(--muted);margin:0 0 1.5rem}
.mono{font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted);
letter-spacing:.04em;text-transform:uppercase}
blockquote{margin:.75rem 0;padding:.6rem .9rem;border-left:3px solid var(--accent);
background:color-mix(in srgb,var(--ink) 4%,transparent)}
blockquote p{margin:0 0 .4rem}
cite{display:block;font-size:.85rem;font-style:normal;color:var(--muted)}
a{color:var(--accent)}
.thin{border:1px dashed var(--rule);padding:.6rem .9rem;margin:.75rem 0;font-size:.9rem;color:var(--muted)}
ol.timeline{list-style:none;padding:0}
ol.timeline li{display:grid;grid-template-columns:4.5rem 1fr;gap:.75rem;
padding:.5rem 0;border-top:1px solid var(--rule)}
ol.timeline b{font:12px/1.5 ui-monospace,monospace;color:var(--muted)}
details.check{margin:.6rem 0;padding:.6rem .9rem;border:1px solid var(--rule)}
details.check summary{cursor:pointer;font-weight:600}
details.check p{margin:.6rem 0 0}
button.reveal{min-height:2.75rem;padding:0 1rem;border:1px solid var(--rule);
background:transparent;color:var(--accent);font:inherit;font-size:.9rem;cursor:pointer}
footer{margin-top:3rem;padding-top:1rem;border-top:1px solid var(--rule);
font-size:.85rem;color:var(--muted)}
@media (max-width:30rem){body{padding:1rem}ol.timeline li{grid-template-columns:1fr}}
`;

// Progressive enhancement only: the page is fully readable with scripting disabled, because
// every check-yourself answer lives in a native <details>. The script only adds "reveal all".
const script = `
document.querySelectorAll('[data-reveal-all]').forEach(function(button){
  button.addEventListener('click', function(){
    var open = button.getAttribute('aria-expanded') === 'true';
    document.querySelectorAll('details.check').forEach(function(item){ item.open = !open; });
    button.setAttribute('aria-expanded', String(!open));
    button.textContent = open ? 'Reveal every answer' : 'Hide every answer';
  });
});
`;

/**
 * A self-contained learning page: inline CSS and JS, no network requests of any kind, every
 * claim quoted with a link back to the source it came from. Safe to open outside Dusori.
 */
export function renderLearnPage(synthesis: TopicSynthesis): string {
  const day = synthesis.generatedAt.slice(0, 10);
  const title = escapeHtml(`Learn — ${synthesis.topicTitle}`);
  const body: string[] = [
    '<main>',
    `<p class="mono">Generated by Dusori · ${escapeHtml(day)}</p>`,
    `<h1>${escapeHtml(synthesis.topicTitle)}</h1>`,
    `<p class="lede">Built from ${synthesis.readCount} of ${synthesis.sourceCount} saved sources, quoting ${synthesis.claimCount} passages. Every passage links back to where it came from.</p>`,
  ];

  if (synthesis.claimCount === 0) {
    body.push(
      '<p>Nothing has been read into quotable passages yet. Save a source, run “Read these”, then create this page again.</p>',
      '</main>',
    );
    return page(title, body.join('\n'), false);
  }

  body.push('<h2>Concepts</h2>');
  for (const cluster of synthesis.clusters) {
    body.push(`<h3>${escapeHtml(cluster.heading)}</h3>`);
    if (cluster.sourceCount === 1) {
      body.push(
        `<p class="thin">Only one source supports this so far — treat it as unconfirmed.</p>`,
      );
    }
    for (const claim of cluster.claims.slice(0, 4)) {
      body.push(
        '<blockquote>',
        `<p>${escapeHtml(claim.text)}</p>`,
        `<cite>${sourceLine(claim.sourceTitle, claim.sourceUrl)}${
          claim.heading ? ` · ${escapeHtml(claim.heading)}` : ''
        }</cite>`,
        '</blockquote>',
      );
    }
  }

  if (synthesis.timeline.length >= 3) {
    body.push('<h2>Timeline</h2>', '<ol class="timeline">');
    for (const entry of synthesis.timeline) {
      body.push(`<li><b>${escapeHtml(entry.year)}</b><span>${sourceLine(entry.title, entry.url)}</span></li>`);
    }
    body.push('</ol>');
  }

  const checks = synthesis.clusters.slice(0, 6);
  if (checks.length > 0) {
    body.push(
      '<h2>Check yourself</h2>',
      '<p>No score is kept and nothing is stored. Answer in your head, then reveal the passage.</p>',
      '<button class="reveal" type="button" data-reveal-all aria-expanded="false">Reveal every answer</button>',
    );
    for (const cluster of checks) {
      const claim = cluster.claims[0];
      if (!claim) continue;
      body.push(
        '<details class="check">',
        `<summary>What do your sources say about ${escapeHtml(cluster.heading.toLowerCase())}?</summary>`,
        `<p>“${escapeHtml(claim.text)}”</p>`,
        `<cite>${sourceLine(claim.sourceTitle, claim.sourceUrl)}</cite>`,
        '</details>',
      );
    }
  }

  if (synthesis.openQuestions.length > 0) {
    body.push('<h2>Open questions</h2>', '<ul>');
    for (const question of synthesis.openQuestions) body.push(`<li>${escapeHtml(question)}</li>`);
    body.push('</ul>');
  }

  if (synthesis.missingLenses.length > 0) {
    body.push(
      `<p class="thin">Nothing saved yet from: ${escapeHtml(synthesis.missingLenses.join(', '))}. That is a gap in coverage, not evidence that nothing exists.</p>`,
    );
  }

  body.push(
    '<footer>Dusori grouped and quoted these passages; it did not verify them. Read the sources before relying on any of this. This file is yours — it works offline and needs no network.</footer>',
    '</main>',
  );

  return page(title, body.join('\n'), checks.length > 0);
}

function page(title: string, body: string, withScript: boolean): string {
  return [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    `<title>${title}</title>`,
    `<style>${styles}</style>`,
    '</head>',
    '<body>',
    body,
    ...(withScript ? [`<script>${script}</script>`] : []),
    '</body>',
    '</html>',
    '',
  ].join('\n');
}
